package com.tdm.domain.model.idea;

import java.io.Serializable;

/**
 * Uniquely identifies a particular cargo. Automatically generated by the
 * application.
 */
@SuppressWarnings("serial")
public class SolutionIdeaId implements Serializable {

    private String id;

    public SolutionIdeaId() {
    }

    public SolutionIdeaId(String id) {
        this.id = id;
    }

    public String getIdString() {
        return id;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        SolutionIdeaId other = (SolutionIdeaId) o;

        return sameValueAs(other);
    }

    @Override
    public int hashCode() {
        return id.hashCode();
    }

    boolean sameValueAs(SolutionIdeaId other) {
        return other != null && this.id.equals(other.id);
    }

    @Override
    public String toString() {
        return id;
    }
}
